Fix regression causing crash when language server command fails exec()
The following Rust program

	use libc::{self, SA_NOCLDWAIT, SA_RESTART, SIGCHLD, SIG_DFL, SIG_IGN};
	use std::{os::unix::process::CommandExt, process::Command};
	fn main() {
	    unsafe {
	        let mut act: libc::sigaction = std::mem::zeroed();
	        act.sa_sigaction = SIG_IGN;
	        libc::sigemptyset(&mut act.sa_mask);
	        act.sa_flags = SA_RESTART | SA_NOCLDWAIT;
	        libc::sigaction(SIGCHLD, &act, std::ptr::null_mut());
	    }
	    let result = unsafe {
	        Command::new("no-such-command")
	            .pre_exec(|| {
	                let mut act: libc::sigaction = std::mem::zeroed();
	                act.sa_sigaction = SIG_DFL;
	                libc::sigemptyset(&mut act.sa_mask);
	                act.sa_flags = 0;
	                libc::sigaction(SIGCHLD, &act, std::ptr::null_mut());
	                Ok(())
	            })
	            .spawn()
	    };
	    assert!(result.is_err()); // no-such-command
	}

crashes an assertion inside spawn():

	thread 'main' panicked at library/std/src/sys/pal/unix/process/process_unix.rs:152:21:
	wait() should either return Ok or panic

Apparently "std::process::Command" and "libc::sigaction" don't mix
very well.  As a workaround, let's stop using SA_NOCLDWAIT and instead
define an equivalent signal handler.