Don't panic if language server startup fails
This panic was propagating to the main kak-lsp process due to the thread
worker drop impl, making me lose all my language servers whenever I
asked for hover info on some random buffer.

Jul 23 02:26:46.855 ERRO panic: panicked at src/thread_worker.rs:30:17, module: kak_lsp:280