Remove window/progress support in favor of $/progress
window/progress was never part of the LSP spec but the new $/progress is.

Suggested usage:

	define-command -override -hidden lsp-handle-progress -params 6 -docstring %{
	  lsp-handle-progress <token> <title> <cancelable> <message> <percentage> <done>
	  Handle progress messages sent from the language server. Override to handle this.
	} %{
	    set-option global lsp_modeline_progress %sh{
	        if ! "$6"; then
	            echo "$2${5:+" ($5%)"}${4:+": $4"}"
	        fi
	    }
	}


Add a workaround for ignoring invalid progress reports, because
clangd-12 sends those (floating point "percentage" instead
of integer). As a result we got error logs like the one below.
That error caused basic features like go-to-definition to stop working.

	ERRO panic: panicked at 'Failed to parse WorkDoneProgressParams params: Error { code: InvalidParams, message: "Invalid params: data did not match any variant of untagged enum ProgressParamsValue.", data: None }', src/progress.rs:35:10, module: kak_lsp:270
	DEBG From server: {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"1/102","percentage":0.98039215686274506}}}, module: kak_lsp::language_server_transport:151
	DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:188
	INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
	DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:87
	DEBG To editor `1453810`: eval -client client0 -verbatim -- lsp-handle-progress 'backgroundIndexProgress' 'indexing' no '0/1' '0' no, module: kak_lsp::editor_transport:80
	INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
	INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
	DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:129
	ERRO Language server error: I[12:09:54.064] clangd version 12.0.1
	I PID: 1454031
	I Working directory: ...
	I argv[0]: clangd
	I Starting LSP over stdin/stdout
	I <-- initialize(0)
	I --> reply:initialize(0) 0 ms
	I <-- initialized
	I <-- textDocument/didOpen
	I <-- textDocument/definition(1)
	I <-- textDocument/codeAction(2)
	I Loaded compilation database from ...
	I --> window/workDoneProgress/create(0)
	I Enqueueing 101 commands for indexing
	I ASTWorker building file ...
	I <-- reply(0)
	I --> $/progress
	I --> $/progress
	I --> $/progress
	I --> $/progress
	I --> $/progress
	I --> $/progress
	E Transport error: Input/output error
	I LSP finished, exiting with status 1
	, module: kak_lsp::language_server_transport:58